exporters:
    opencensus:
        endpoint: "testcoordinator:10001"

    jaeger:
        collector_endpoint: "http://traceui:14268/api/traces"

receivers:
    opencensus:
        address: "0.0.0.0:55678"
