exporters:
    ocagent:
        endpoint: "http://testcoordinator:10001"

    jaeger:
        collector_endpoint: "http://traceui:14268/api/traces"

receivers:
    opencensus:
        address: "127.0.0.1:55678"
