# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ocagent
spec:
  template:
    metadata:
      labels:
        app: ocagent
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/opencensus-interoptest/ocagent
        imagePullPolicy: Never
        ports:
        - containerPort: 55678
          name: ocagent
        env:
        - name: PORT
          value: "55678"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
#        readinessProbe:
#          tcpSocket:
#            port: 55678
#          initialDelaySeconds: 5
#          periodSeconds: 10
#        livenessProbe:
#          tcpSocket:
#            port: 55678
#          initialDelaySeconds: 10
#          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ocagent
spec:
  type: ClusterIP
  selector:
    app: ocagent
  ports:
  - name: ocagent
    port: 55678
    targetPort: 55678
