# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: traceui
spec:
  template:
    metadata:
      labels:
        app: traceui
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/opencensus-interoptest/traceui
        imagePullPolicy: Never
        ports:
        - containerPort: 9411
          name: zipkin
        - containerPort: 5775
          name: zipkin-thrift
          protocol: UDP
        - containerPort: 6831
          name: thrift
          protocol: UDP
        - containerPort: 6832
          name: bin-thrift
          protocol: UDP
        - containerPort: 5778
          name: config
          protocol: TCP
        - containerPort: 16686
          name: frontend
          protocol: TCP
        - containerPort: 14268
          name: thrift-direct
          protocol: TCP

        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 400Mi
#        readinessProbe:
#          tcpSocket:
#            port: 9411
#          initialDelaySeconds: 5
#          periodSeconds: 10
#        livenessProbe:
#          tcpSocket:
#            port: 9411
#          initialDelaySeconds: 10
#          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: traceui
spec:
  type: ClusterIP
  selector:
    app: traceui
  ports:
  - name: zipkin
    port: 9411
    targetPort: 9411
  - name: zipkin-thrift
    port: 5775
    targetPort: 5775
    protocol: UDP
  - name: jaeger-thrift
    port: 6831
    targetPort: 6831
    protocol: UDP
  - name: jaeger-binary-thrift
    port: 6832
    targetPort: 6832
    protocol: UDP
  - name: config
    port: 5778
    targetPort: 5778
    protocol: TCP
  - name: frontend
    port: 16686
    targetPort: 16686
    protocol: TCP
  - name: jaeger-thrift-direct
    port: 14268
    targetPort: 14268
    protocol: TCP
